#!/bin/bash
#
# CushionFoamz Daily Reddit Conversation Updater
# Run this daily to update conversation tracker
# Usage: ./scripts/update-cushion-conversations.sh
#

TODAY=$(date +%Y-%m-%d)
OUTPUT_DIR="agents/spike/outputs/cushionfoamz"
CAMPAIGN_DIR="business/cushionfoamz/01-marketing/reddit-campaigns"

echo "🎯 Updating CushionFoamz Conversations for $TODAY"
echo "================================================"

# Ensure directories exist
mkdir -p "$OUTPUT_DIR"
mkdir -p "$CAMPAIGN_DIR"

# Create today's conversation file
cat > "$OUTPUT_DIR/${TODAY}-conversations.md" << EOF
# CushionFoamz Reddit Conversations — $TODAY
**Status:** Active monitoring for response opportunities  
**Goal:** 3 quality responses today  
**Last Updated:** $(date +"%I:%M %p")

---

## 🔥 PRIORITY CONVERSATIONS (Respond First)

### 1. [Conversation Title Placeholder]
- **Subreddit:** r/[subreddit]
- **URL:** [Reddit URL]
- **Posted:** [Time] ago
- **Engagement:** [X] upvotes, [Y] comments
- **Topic:** [Brief description]
- **Status:** 🟡 NEW

**Pre-written Response:**
\`\`\`
[Response will be generated by Johnny 5]
\`\`\`

**Action Checklist:**
- [ ] Open URL
- [ ] Read thread
- [ ] Post response
- [ ] Mark complete

---

### 2. [Conversation Title Placeholder]
- **Subreddit:** r/[subreddit]
- **URL:** [Reddit URL]
- **Posted:** [Time] ago
- **Engagement:** [X] upvotes, [Y] comments
- **Topic:** [Brief description]
- **Status:** 🟡 NEW

**Pre-written Response:**
\`\`\`
[Response will be generated by Johnny 5]
\`\`\`

**Action Checklist:**
- [ ] Open URL
- [ ] Read thread
- [ ] Post response
- [ ] Mark complete

---

### 3. [Conversation Title Placeholder]
- **Subreddit:** r/[subreddit]
- **URL:** [Reddit URL]
- **Posted:** [Time] ago
- **Engagement:** [X] upvotes, [Y] comments
- **Topic:** [Brief description]
- **Status:** 🟡 NEW

**Pre-written Response:**
\`\`\`
[Response will be generated by Johnny 5]
\`\`\`

**Action Checklist:**
- [ ] Open URL
- [ ] Read thread
- [ ] Post response
- [ ] Mark complete

---

## 📊 DAILY STATS

| Metric | Target | Today |
|--------|--------|-------|
| Conversations Found | 3+ | 0 |
| Responses Posted | 3 | 0 |
| Upvotes Received | 2+ | 0 |
| Website Clicks | - | 0 |

---

## 📝 NOTES

- **Spike Search Queries Used:**
  - "sagging couch" OR "couch cushion"
  - "outdoor cushion" OR "patio furniture"
  - "window seat cushion" OR "bench cushion"
  - "boat cushion" OR "marine foam"
  - "reupholster" OR "replace foam"

- **Subreddits Monitored:**
  - r/DIY
  - r/HomeImprovement
  - r/woodworking
  - r/upholstery
  - r/ThriftStoreHauls
  - r/Boating
  - r/RVLiving

---

## ✅ COMPLETED TODAY

_None yet — update as you post responses_

---

*Next Update: Tomorrow 8 AM*  
*Quick Access: action-dashboard.html*
EOF

echo "✅ Created: $OUTPUT_DIR/${TODAY}-conversations.md"

# Also archive to campaign folder
cp "$OUTPUT_DIR/${TODAY}-conversations.md" "$CAMPAIGN_DIR/"

echo "✅ Archived to: $CAMPAIGN_DIR/"

# Update the action-dashboard.html conversation section (placeholder for now)
echo "📝 Note: Update action-dashboard.html with today's conversations"

# Add to calendar reminder
echo ""
echo "📅 CALENDAR REMINDER:"
echo "   Add to Google Calendar at 2 PM:"
echo "   'Post 3 Reddit responses — check action-dashboard.html'"
echo "   Link: file:///Users/rubenruiz/.openclaw/workspace/action-dashboard.html"
echo ""
echo "⚡ Done! Open action-dashboard.html to see today's conversations."
